[tox]
requires = tox>=4
envlist = lint, docs, py3{9,10,11,12,13}
isolated_build = true

[testenv]
description =
    Run tests under {basepython}
    cov: with coverage

setenv =
    cov: CYTHON_TEST_MACROS=1

passenv =
    DPKG_DISTRO_DEV_ROOT,
    PKG_CONFIG_PATH,
    PKG_CONFIG_SYSROOT_DIR,
    PKG_CONFIG
    BMQ_BROKER_URI

whitelist_externals = make

deps =
    pip>=19.0.3
    -rrequirements-test.txt

commands =
    {basepython} -c 'import sys; print("\n".join(sys.path))'
    make PYTEST_ARGS='-vvv --showlocals --color=yes {posargs} --junit-xml={toxworkdir}/{envname}_integration.xml ' check

commands_cov = {basepython} -m pytest -v --timeout=30 --cov --cov-report=term --cov-fail-under=100 --cov-append --junitxml={toxworkdir}/{envname}_integration.xml --cov-report=xml:{toxworkdir}/coverage.xml

[testenv:.package]
description = Isolated build environment
basepython = python3.13

[testenv:py313-cov]
usedevelop = True
commands = {[testenv]commands_cov}
deps = -rrequirements-test-coverage.txt

[testenv:lint]
description = Run all linters
basepython = python3.13
deps = -rrequirements-lint-docs.txt
skip_install = true
allowlist_externals = clang-format
commands =
    {basepython} -m black --check --verbose src tests examples setup.py
    {basepython} -m flake8 --config={toxinidir}/.flake8.cython src
    {basepython} -m flake8 --config={toxinidir}/.flake8 src
    {basepython} -m flake8 --config={toxinidir}/tests/.flake8 tests
    {basepython} -m flake8 --config={toxinidir}/tests/.flake8 examples
    {basepython} -m isort --check-only --settings-path={toxinidir}/.isort.cfg src tests examples setup.py
    {basepython} -m mypy --strict examples src
    clang-format --Werror --dry-run src/cpp/*

[testenv:lint-python]
description = Run lint checker on Python files
basepython = python3.13
deps = flake8
skip_install = true
commands = {basepython} -m flake8 --config={toxinidir}/.flake8 src

[testenv:lint-cython]
description = Run lint checker on Cython files
basepython = python3.13
deps = flake8
skip_install = true
commands = {basepython} -m flake8 --config={toxinidir}/.flake8.cython src

[testenv:lint-types]
description = Run mypy checker on examples
basepython = python3.13
deps =
    mypy
commands = {basepython} -m mypy --strict {posargs:src/blazingmq examples}

[testenv:black]
description = Check that python files are formatted with black
basepython = python3.13
deps = black
skip_install = true
commands = {basepython} -m black --check --verbose src tests

[testenv:format]
description = Auto-format Python and C++ files
basepython = python3.13
deps =
    black
    isort
skip_install = true
allowlist_externals = clang-format
commands =
    {basepython} -m black --verbose src tests examples setup.py
    {basepython} -m isort --settings-path={toxinidir}/.isort.cfg src tests examples setup.py
    clang-format --Werror -i src/cpp/*

[testenv:docs]
description = Generate library documentation
basepython = python3.13
deps = -rrequirements-lint-docs.txt
commands = make -C docs html
           {basepython} -c 'print("documentation available under file://{toxworkdir}/docs_out/index.html")'

[testenv:dist]
description = Build source distribution
basepython = python3.13
deps = setuptools
skip_install = true
commands = {basepython} setup.py sdist

[testenv:gen-news]
description = Generate changelog with towncrier
basepython = python3.13
deps = towncrier
skip_install = true
commands = {basepython} -m towncrier build

[testenv:lint-markdown]
description = Lint markdown files
basepython = python3.13
skip_install = true
allowlist_externals = markdownlint
commands = markdownlint '**/*.md'
