name: DCO check
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"

permissions:
  contents: read

jobs:
  commits_check_job:
    permissions:
      pull-requests: read  # for tim-actions/get-pr-commits to get list of commits from the PR
    runs-on: ubuntu-slim
    name: Commits Check
    steps:
      - name: Get PR Commits
        id: "get-pr-commits"
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: DCO Check
        uses: tim-actions/dco@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
